<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<?php $SITE_NAME = "The No Bull"; ?>
<?php $PAGE_TITLE = "About"; ?>

<html lang="en">
<?php include( "assets/phtml/head.phtml" ); ?>
<body class="is-preload">
<div id="wrapper">
    <?php include( "assets/phtml/header.phtml" ); ?>
    <?php include( "assets/phtml/menu.phtml" ); ?>

    <div id="main">
        <div class="inner">
            <h1><?php echo $PAGE_TITLE; ?></h1>
            <span class="image main"><img src="images/pic13.jpg" alt="" /></span>

            <h2>Vision</h2>

            <ul id="principles" class="alt">
                <li>We believe that people are people.</li>
                <li>People are not information to be sold.</li>
                <li>People are not to be deceived.</li>
            </ul>

            <p>
                The No Bull is a community driven platform that connects people with the information they love. It does
                this with promise that the information provided contains no ads, no tracking and no data mining. Simply
                put no bull sh*t.
            </p>

            <p>
                We also believe that information is valuable and it's creators deserve to be compensated appropriately.
                Compensated in a way that is transparent and benefits the community.
            </p>

            <h2>How</h2>
            <p>
                We ask the community to recommend apps and sites that they love. Apps and sites that contain, no ads, no
                tracking and no data mining. Simply put no bull sh*t.
            </p>

            <p>
                Premium, paid apps and sites are not discouraged. As long as they clearly define how funds are
                collected, used and contributed back to the community. Simply put no bull sh*t.
            </p>
        </div>
    </div>

    <?php include( "assets/phtml/footer.phtml" ); ?>
</div>

<?php include( "assets/phtml/scripts.phtml" ); ?>

</body>
</html>