<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<?php $SITE_NAME = "The No Bull"; ?>
<?php $PAGE_TITLE = "About"; ?>

<html lang="en">
<?php include( "assets/phtml/head.phtml" ); ?>
<body class="is-preload">
<div id="wrapper">
    <?php include( "assets/phtml/header.phtml" ); ?>
    <?php include( "assets/phtml/menu.phtml" ); ?>

    <div id="main">
        <div class="inner">
            <h1><?php echo $PAGE_TITLE; ?></h1>
            <span class="image main"><img src="images/pic13.jpg" alt="" /></span>
            <p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis
                dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet.
                Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia
                malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien
                risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit
                tristique.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent
                taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu
                nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies
                condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem
                mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et
                netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque
                aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
            <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet
                dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo
                mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis
                elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
        </div>
    </div>

    <?php include( "assets/phtml/footer.phtml" ); ?>
</div>

<?php include( "assets/phtml/scripts.phtml" ); ?>

</body>
</html>